#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

# Install system packages
apt-get update -qq
apt-get install -y -qq \
    git curl build-essential openssh-server \
    ca-certificates netcat-openbsd iptables < /dev/null

# Create user (no sudo, no password)
useradd -m -s /bin/bash user
passwd -l user

# Pre-install VS Code Server if commit hash was provided at build time
if [ -n "${VSCODE_COMMIT:-}" ]; then
    echo "Installing VS Code Server (commit: $VSCODE_COMMIT)..."
    ARCH=$(dpkg --print-architecture)
    case "$ARCH" in
        amd64) VSCODE_ARCH="x64" ;;
        arm64) VSCODE_ARCH="arm64" ;;
        *) VSCODE_ARCH="$ARCH" ;;
    esac
    SERVER_URL="https://update.code.visualstudio.com/commit:${VSCODE_COMMIT}/server-linux-${VSCODE_ARCH}/stable"
    SERVER_DIR="/home/user/.vscode-server/cli/servers/Stable-${VSCODE_COMMIT}/server"
    su - user -c "mkdir -p '$SERVER_DIR' && curl -sSL '$SERVER_URL' | tar xz -C '$SERVER_DIR' --strip-components=1" \
        || echo "Warning: failed to pre-install VS Code Server"
fi

# Configure SSH (key-based auth only)
mkdir -p /run/sshd
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config

# Enable SSH to start on boot
systemctl enable ssh 2>/dev/null || true

# Create mount points for shared volumes
mkdir -p /shared/git
chown user:user /shared/git

# Create mount point for relay socket
mkdir -p /bubble

# Install bubble-in-bubble relay client
cat > /usr/local/lib/bubble-relay-client.py << 'PYEOF'
"""Relay client for bubble-in-bubble. Sends a target to the host relay daemon."""
import json
import socket
import sys

def main():
    if len(sys.argv) < 3:
        print("Usage: bubble-relay-client.py <socket_path> <target>", file=sys.stderr)
        sys.exit(1)
    sock_path = sys.argv[1]
    target = sys.argv[2]

    # Read relay token (generated by host, injected at container creation)
    token = ""
    try:
        with open("/bubble/relay-token") as f:
            token = f.read().strip()
    except FileNotFoundError:
        print("Relay token not found. Container may need to be recreated.", file=sys.stderr)
        sys.exit(1)

    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.settimeout(30)
        s.connect(sock_path)
        request = json.dumps({"target": target, "token": token})
        s.sendall(request.encode())
        s.shutdown(socket.SHUT_WR)
        # Read response until EOF
        chunks = []
        while True:
            chunk = s.recv(4096)
            if not chunk:
                break
            chunks.append(chunk)
        data = b"".join(chunks)
        if not data:
            print("Relay error: no response from daemon", file=sys.stderr)
            sys.exit(1)
        response = json.loads(data)
        print(response.get("message", ""))
        sys.exit(0 if response.get("status") == "ok" else 1)
    except Exception as e:
        print(f"Relay error: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        s.close()

if __name__ == "__main__":
    main()
PYEOF

cat > /usr/local/bin/bubble << 'STUBEOF'
#!/bin/bash
SOCK="/bubble/relay.sock"
if [ ! -S "$SOCK" ]; then
    echo "bubble-in-bubble is not enabled." >&2
    echo "Run 'bubble relay enable' on the host to enable it." >&2
    exit 1
fi
if [ -z "$1" ]; then
    echo "Usage: bubble <target>" >&2
    exit 1
fi
exec python3 /usr/local/lib/bubble-relay-client.py "$SOCK" "$1"
STUBEOF
chmod +x /usr/local/bin/bubble

# Clean up
apt-get clean
rm -rf /var/lib/apt/lists/*

echo "Base image setup complete."
