#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

# Install system packages
echo "BUBBLE_PROGRESS: Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
    git curl build-essential cmake openssh-server \
    ca-certificates netcat-openbsd iptables < /dev/null

# Create user (no sudo, no password)
echo "BUBBLE_PROGRESS: Creating user account..."
useradd -m -s /bin/bash user
passwd -l user

# Configure SSH (key-based auth only)
echo "BUBBLE_PROGRESS: Configuring SSH..."
mkdir -p /run/sshd
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config

# Enable SSH to start on boot
systemctl enable ssh 2>/dev/null || true

# Create mount points for shared volumes
mkdir -p /shared/git
chown user:user /shared/git

# Create mount point for relay socket
mkdir -p /bubble

echo "BUBBLE_PROGRESS: Installing relay client..."
# Install bubble-in-bubble relay client
cat > /usr/local/lib/bubble-relay-client.py << 'PYEOF'
"""Relay client for bubble-in-bubble. Sends a target to the host relay daemon."""
import json
import socket
import sys

def main():
    if len(sys.argv) < 3:
        print("Usage: bubble-relay-client.py <socket_path> <target>", file=sys.stderr)
        sys.exit(1)
    sock_path = sys.argv[1]
    target = sys.argv[2]

    # Read relay token (generated by host, injected at container creation)
    token = ""
    try:
        with open("/bubble/relay-token") as f:
            token = f.read().strip()
    except FileNotFoundError:
        print("Relay token not found. Container may need to be recreated.", file=sys.stderr)
        sys.exit(1)

    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.settimeout(30)
        s.connect(sock_path)
        request = json.dumps({"target": target, "token": token})
        s.sendall(request.encode())
        s.shutdown(socket.SHUT_WR)
        # Read response until EOF
        chunks = []
        while True:
            chunk = s.recv(4096)
            if not chunk:
                break
            chunks.append(chunk)
        data = b"".join(chunks)
        if not data:
            print("Relay error: no response from daemon", file=sys.stderr)
            sys.exit(1)
        response = json.loads(data)
        print(response.get("message", ""))
        sys.exit(0 if response.get("status") == "ok" else 1)
    except Exception as e:
        print(f"Relay error: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        s.close()

if __name__ == "__main__":
    main()
PYEOF

cat > /usr/local/bin/bubble << 'STUBEOF'
#!/bin/bash
SOCK="/bubble/relay.sock"
if [ ! -S "$SOCK" ]; then
    echo "bubble-in-bubble is not enabled." >&2
    echo "Run 'bubble relay enable' on the host to enable it." >&2
    exit 1
fi
if [ -z "$1" ]; then
    echo "Usage: bubble <target>" >&2
    exit 1
fi
exec python3 /usr/local/lib/bubble-relay-client.py "$SOCK" "$1"
STUBEOF
chmod +x /usr/local/bin/bubble

# Add shell hook to consume build marker file (for non-VS Code editors).
# The VS Code extension (bubble.lean-cache) handles this for VS Code.
# For shell/emacs/neovim, this .profile snippet runs the build in background
# on first login and points the user to the log file.
cat >> /home/user/.profile << 'PROFILEEOF'

# bubble: auto-run build command if marker file exists.
# Guard on SSH_CONNECTION to avoid triggering during provisioning
# (su - user -c "..." sources .profile but doesn't set SSH_CONNECTION).
if [ -n "$SSH_CONNECTION" ] && [ -f "$HOME/.bubble-fetch-cache" ]; then
    _bubble_cmd=$(cat "$HOME/.bubble-fetch-cache")
    rm -f "$HOME/.bubble-fetch-cache"
    if [ -n "$_bubble_cmd" ]; then
        echo "Build started in background..."
        echo "  Run 'tail -f ~/build.log' to monitor progress."
        nohup bash -c "$_bubble_cmd" > "$HOME/build.log" 2>&1 &
    fi
    unset _bubble_cmd
fi
PROFILEEOF
chown user:user /home/user/.profile

# Clean up
echo "BUBBLE_PROGRESS: Cleaning up..."
apt-get clean
rm -rf /var/lib/apt/lists/*

echo "Base image setup complete."
